version: "3.9"
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile   
  #   working_dir: /app
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_DB=0
  #     - REDIS_PASSWORD=
  #   depends_on:
  #     - redis
  #   networks:
  #     - api-net
  database:
    image: "postgres:14.5"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
