# fly.toml app configuration file generated for bbg-api on 2024-11-01T22:28:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bbg-api'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
