# fly.toml app configuration file generated for tournament-live-scoring on 2025-07-01T17:36:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tournament-live-scoring'
primary_region = 'iad'

[build]
  [build.args]
    HOST='tournament-live-scoring.fly.dev'

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
min_machines_running = 1
auto_stop_machines = "off"

processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2

[mounts]
destination = "/pb_data"
source = "pb_data"
